### ISSUE TITLE
SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by tdwesten** [mdibaiee/node-telegram-api#2]
Hi, when i run demo.js I got this error: 

``` javascript
smartBot.start().then(() => {
                       ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

What's going wrong? 

Thanks for build this package!

**Comment by mdibaiee** [comment]
Please use node > 0.12 with `--harmony` flag on and see if it works.

I'm going to pre-transpile this in the new upcoming version.

**Comment by tdwesten** [comment]
Oke, i have updated my node version, but now i got this error: 

``` javascript
(function (exports, require, module, __filename, __dirname) { import API from
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/thomasvanderwesten/server/ns_bot/node_modules/telegram-api/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:177:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/thomasvanderwesten/server/ns_bot/node_modules/telegram-api/index.js:2:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/thomasvanderwesten/server/ns_bot/demo.js:1:73)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

(i'am running now node v0.12.5)
Thanks for your help :+1:

**Comment by mdibaiee** [comment]
have you run `npm install` ?

**Comment by mdibaiee** [comment]
See the new update.
