### ISSUE TITLE
Error occurs at random times: Message undefined

### ISSUE THREAD

**Issue by austinhuang0131** [mdibaiee/node-telegram-api#31]
```
TypeError: Cannot read property 'chat' of undefined
    at /var/lib/openshift/581204327628e191f2000152/app-root/runtime/repo/node_modules/telegram-api/types/Base.js:86:27
    at Array.find (native)
    at Bot.listener (/var/lib/openshift/581204327628e191f2000152/app-root/runtime/repo/node_modules/telegram-api/types/Base.js:78:31)
    at emitOne (events.js:101:20)
    at Bot.emit (events.js:188:7)
    at /var/lib/openshift/581204327628e191f2000152/app-root/runtime/repo/node_modules/telegram-api/build/functions/poll.js:12:9
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```
[Source](https://github.com/austinhuang0131/metagon). Could happen in any `bot.command` or `bot.get`.

**Comment by austinhuang0131** [comment]
#32
